export interface DesignData {
  id: string;
  name: string;
  for: string;
  type: string;
  img: string;
}

const PortfolioDesign: DesignData[] = [
  {
    id: "111",
    name: "Poster Fashion",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FASION.png",
  },
  {
    id: "112",
    name: "Poster Fashion",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FASHION%202.png",
  },
  {
    id: "113",
    name: "Poster Fashion",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FASHION%203.png",
  },
  {
    id: "114",
    name: "Poster Fashion",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FASHION%204.png",
  },
  {
    id: "115",
    name: "Poster Fashion",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FASION%205.png",
  },
  {
    id: "116",
    name: "Poster Food",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FOOD%202.png",
  },
  {
    id: "116",
    name: "Poster Food",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FOOD.png",
  },
  {
    id: "116",
    name: "Travel Web",
    for: "",
    type: "Web Design",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Travel.png",
  },
  {
    id: "1",
    name: "D'cut Barbershop",
    for: "Comission",
    type: "Logo",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/logo.png",
  },
  {
    id: "2",
    name: "Package Coffe",
    for: "",
    type: "package",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Packaging%20Product%20Design.jpg",
  },
  {
    id: "3",
    name: "Package Logo",
    for: "",
    type: "Package",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/packaging%20design.jpg",
  },
  {
    id: "4",
    name: "Jamu Banner",
    for: "Comission",
    type: "Banner",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/banner%20product%20design.png",
  },
  {
    id: "5",
    name: "Travel Poster",
    for: "Comission",
    type: "Banner",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/travel%20poster.png",
  },
  {
    id: "6",
    name: "Ayam Gepuk",
    for: "Comission",
    type: "Banner",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/ayam%20gepuk%20brand.png",
  },
  {
    id: "7",
    name: "Discount",
    for: "",
    type: "Banner",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/banner%20design.jpg",
  },
  {
    id: "8",
    name: "Coffeshop Web",
    for: "",
    type: "Web Design",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Coffeshop%20Website%20Design.png",
  },
  {
    id: "9",
    name: "Game Center Web",
    for: "",
    type: "Web Design",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Game%20Center%20Web%20Design.png",
  },
  {
    id: "10",
    name: "ShopNow Web Design",
    for: "",
    type: "Web Design",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/ShopNow%20Website%20Design.png",
  },
  {
    id: "11",
    name: "Website Design",
    for: "",
    type: "Web Design",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Website%20Design.png",
  },
  {
    id: "12",
    name: "Food Menu",
    for: "",
    type: "Catalog",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/catalog%20food%20menu.jpg",
  },
  {
    id: "13",
    name: "Jamu Menu",
    for: "Comission",
    type: "Catalog",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/catalog%20menu%20design.png",
  },
  {
    id: "14",
    name: "Catalog Product",
    for: "",
    type: "Catalog",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Catalog%20Product%20Design.png",
  },
  {
    id: "15",
    name: "Wedding Invitation",
    for: "Comission",
    type: "Invitation",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/wedding%20invitation%202.png",
  },
  {
    id: "16",
    name: "Wedding Invitation 2",
    for: "",
    type: "Invitation",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/wedding%20invitation.png",
  },
  {
    id: "17",
    name: "Bussiness Card",
    for: "",
    type: "Invitation",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Business%20Card.png",
  },
  {
    id: "18",
    name: "Product Discount",
    for: "",
    type: "Social Media",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/product%20poster.png",
  },
  {
    id: "19",
    name: "Event Poster",
    for: "",
    type: "Social Media",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/event%20poster.jpg",
  },
  {
    id: "20",
    name: "Social Media Template",
    for: "",
    type: "Social Media",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/social%20media.jpg",
  },
  {
    id: "21",
    name: "Illustration",
    for: "",
    type: "Illustration",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Illustration%20Design.png",
  },
  {
    id: "22",
    name: "Flat Design",
    for: "",
    type: "Illustration",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/flat%20design.jpg",
  },
  {
    id: "23",
    name: "Team Football",
    for: "Comission",
    type: "Branding",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/team%20football.png",
  },
  {
    id: "24",
    name: "Tshirt Design",
    for: "",
    type: "Tshirt",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Tshirt%20Design.png",
  },
];

export default PortfolioDesign;
