export interface DesignData {
  id: string;
  name: string;
  for: string;
  type: string;
  img: string;
}

const PortfolioDesign: DesignData[] = [
  {
    id: "110",
    name: "Package Box",
    for: "",
    type: "Package",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/qq.png",
  },
  {
    id: "107",
    name: "Fashion Tag",
    for: "",
    type: "Fashion",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/ww.png",
  },
  {
    id: "108",
    name: "Cup Package",
    for: "",
    type: "Package",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/rr.png",
  },
  {
    id: "109",
    name: "Coffee Package",
    for: "",
    type: "Package",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/coffee%20pacage%20resize.png",
  },
  {
    id: "",
    name: "Coffee Package",
    for: "",
    type: "Package",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/Coffee%20Bags%20Mockups.png",
  },
  {
    id: "111",
    name: "Poster Fashion",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FASION.png",
  },
  {
    id: "112",
    name: "Poster Fashion",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FASHION%202.png",
  },
  {
    id: "113",
    name: "Poster Fashion",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FASHION%203.png",
  },
  {
    id: "114",
    name: "Poster Fashion",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FASHION%204.png",
  },
  {
    id: "115",
    name: "Poster Fashion",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FASION%205.png",
  },
  {
    id: "",
    name: "Catalog",
    for: "",
    type: "Catalog",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/aa.png",
  },
  {
    id: "",
    name: "Catalog",
    for: "",
    type: "Catalog",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/bb.png",
  },
  {
    id: "",
    name: "Catalog",
    for: "",
    type: "Catalog",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/cc.png",
  },
  {
    id: "116",
    name: "Poster Food",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FOOD%202.png",
  },
  {
    id: "116",
    name: "Poster Food",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/POSTER%20-%20FOOD.png",
  },
  {
    id: "116",
    name: "Poster Webinar",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/a.png",
  },
  {
    id: "116",
    name: "Invitation",
    for: "",
    type: "Invitation",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/Royal%20Invitation%201%20x%201.png",
  },
  {
    id: "116",
    name: "Invitation",
    for: "",
    type: "Invitation",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/Royal%20Invitation%20v2%201%20x%201.png",
  },
  {
    id: "116",
    name: "Invitation",
    for: "",
    type: "Invitation",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/Untitled-1-02.png",
  },
  {
    id: "116",
    name: "Invitation",
    for: "",
    type: "Invitation",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/Untitled-1-01.png",
  },
  {
    id: "",
    name: "Tshirt Design",
    for: "",
    type: "Tshirt",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/2-01.png",
  },
  {
    id: "116",
    name: "Tshirt Design",
    for: "",
    type: "Tshirt",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/b.png",
  },
  {
    id: "116",
    name: "Tshirt Design",
    for: "",
    type: "Tshirt",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/c.png",
  },
  {
    id: "116",
    name: "Tshirt Design",
    for: "",
    type: "Tshirt",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/f.png",
  },
  {
    id: "116",
    name: "Tshirt Design",
    for: "",
    type: "Tshirt",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/g.png",
  },
  {
    id: "116",
    name: "Tshirt Design",
    for: "",
    type: "Tshirt",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/h.png",
  },
  {
    id: "116",
    name: "Tshirt Design",
    for: "",
    type: "Tshirt",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/D3%20GK.png",
  },
  {
    id: "116",
    name: "Tshirt Design",
    for: "",
    type: "Tshirt",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/D3.png",
  },
  {
    id: "116",
    name: "Food Menu",
    for: "",
    type: "Menu",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Untitled-2-01.png",
  },
  {
    id: "116",
    name: "Food Menu",
    for: "",
    type: "Menu",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Untitled-2-02.png",
  },
  {
    id: "",
    name: "Poster",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/a.png",
  },
  {
    id: "",
    name: "Poster",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/b.png",
  },
  {
    id: "",
    name: "Poster",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/c.png",
  },
  {
    id: "",
    name: "Poster",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/d.png",
  },
  {
    id: "",
    name: "Poster",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/e.png",
  },
  {
    id: "",
    name: "Poster",
    for: "",
    type: "Poster",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/new/f.png",
  },
  {
    id: "8",
    name: "Coffeshop Web",
    for: "",
    type: "Web Design",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Desktop%20-%201.png",
  },
  {
    id: "116",
    name: "Travel Web",
    for: "",
    type: "Web Design",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Travel.png",
  },
  {
    id: "116",
    name: "NikeShop",
    for: "",
    type: "Web Design",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/NikeShop.png",
  },
  {
    id: "1",
    name: "D'cut Barbershop",
    for: "Comission",
    type: "Logo",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/logo.png",
  },
  {
    id: "3",
    name: "Package Logo",
    for: "",
    type: "Package",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/packaging%20design.jpg",
  },
  {
    id: "4",
    name: "Jamu Banner",
    for: "Comission",
    type: "Banner",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/banner%20product%20design.png",
  },
  {
    id: "6",
    name: "Ayam Gepuk",
    for: "Comission",
    type: "Banner",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/ayam%20gepuk%20brand.png",
  },
  {
    id: "10",
    name: "ShopNow Web Design",
    for: "",
    type: "Web Design",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/ShopNow%20Website%20Design.png",
  },
  {
    id: "13",
    name: "Jamu Menu",
    for: "Comission",
    type: "Catalog",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/catalog%20menu%20design.png",
  },
  {
    id: "17",
    name: "Bussiness Card",
    for: "",
    type: "Invitation",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Business%20Card.png",
  },
  {
    id: "19",
    name: "Event Poster",
    for: "",
    type: "Social Media",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/event%20poster.jpg",
  },
  {
    id: "21",
    name: "Illustration",
    for: "",
    type: "Illustration",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/Illustration%20Design.png",
  },
  {
    id: "22",
    name: "Flat Design",
    for: "",
    type: "Illustration",
    img: "https://raw.githubusercontent.com/zidan-bsd/assets-resource/main/graphic%20design%20portfolio/flat%20design.jpg",
  },
];

export default PortfolioDesign;
